### ISSUE TITLE
test failures with jdk1.6.0_20 on 32-bit Fedora 8

### ISSUE THREAD

**Issue by dougm** [moonpolysoft/scromium#1]
build console log includes system properties listing: http://hudson.hyperic.com/job/scromium-master/3/console
Let me know if I can provide more info.  I could also setup the build job to run on just about any other platform instead.

**Comment by moonpolysoft** [comment]
It looks like the problem with rollspec is that the default charset on my mac is MacRoman, and it's likely UTF-8 on your server.  I will update the roll function to deal with character codepoints in utf-8 instead of screwing around at the byte level.

**Comment by moonpolysoft** [comment]
String rolling should using character points, not byte manipulation due to varying charsets.  Closed by 3117d86a0ad25420d77163675a3c74b1b443d636.
